In [ ]:
'''
2025년 9월 3일 화이팅입니다!!

이번주는 수강 정정기간이라 여러모로 정신없는 주간이었다.
파이썬 수업과 AI수업을 모두 듣고 싶은 욕심에 무리한 수업일정을 짠 건 아닌지 걱정되기도 한다.
다행히도 지금은 다소 정리되어 공부시간을 확보할 수 있을 것 같다.
다시 열심히 달려보자!!!
'''

# 데이터 전처리 - 구조변경 : 그룹화, 집계, 데이터병합과 추가

In [ ]:
import pandas as pd

# 데이터 로드
file_path = "datasets/heart.csv"
df = pd.read_csv(file_path)

# 컬럼명 변경
df.columns = ['나이', '성별', '흉통유형', '안정시혈압', '콜레스테롤', '공복혈당', '심전도',
              '최대심박수', '운동유발협심증', 'ST우울증', '운동후ST경사', '주요혈관수',
              '결함유형', '심장질환여부']

# 데이터 확인
print("변경된 데이터프레임 컬럼명:")
print(df.columns)
print("\n데이터 상위 5개 행:")
print(df.head())

변경된 데이터프레임 컬럼명:
Index(['나이', '성별', '흉통유형', '안정시혈압', '콜레스테롤', '공복혈당', '심전도', '최대심박수', '운동유발협심증',
       'ST우울증', '운동후ST경사', '주요혈관수', '결함유형', '심장질환여부'],
      dtype='object')

데이터 상위 5개 행:
   나이  성별  흉통유형  안정시혈압  콜레스테롤  공복혈당  심전도  최대심박수  운동유발협심증  ST우울증  운동후ST경사  \
0  63   1     3    145    233     1    0    150        0    2.3        0
1  37   1     2    130    250     0    1    187        0    3.5        0
2  41   0     1    130    204     0    0    172        0    1.4        2
3  56   1     1    120    236     0    1    178        0    0.8        2
4  57   0     0    120    354     0    1    163        1    0.6        2

   주요혈관수  결함유형  심장질환여부
0      0     1       1
1      0     2       1
2      0     2       1
3      0     2       1
4      0     2       1

## 1. 그룹화 및 집계

In [ ]:
'''
그룹화(Grouping)는 데이터를 특정 기준에 따라 묶는 작업이고
집계(Aggregation)은 묶인 데이터를 요약하는 작업이다.
이를 통해 평균, 합계, 개수등의 통계를 도출할 수 있다.

    groupby()
        pandas 라이브러리의 메서드로, 데이터를 특정 열 기준으로 그룹화한다
    
    grouped.agg()
        마찬가지로 pandas 라이브러리의 메서드로, 여러 집계 함수를 동시에 적용한다
'''


'''
그룹화(groupby) → 인덱스(그래프의 왼쪽) 모양 결정
집계(agg) → 컬럼(그래프의 위쪽) 모양 결정

그룹화는 "어떻게 나눌까?"(인덱스), 집계는 "무엇을 계산할까?"(컬럼)
'''

In [6]:
# 1. 성별 기준 데이터 그룹화
grouped = df.groupby('성별')

print('성별 그룹화된 데이터:')
print(grouped.size())        ## groupby()는 데이터프레임이 아닌 시리즈를 반환함

print('그룹별 평균')
print(grouped.mean())

성별 그룹화된 데이터:
성별
0     96
1    207
dtype: int64
그룹별 평균
           나이      흉통유형       안정시혈압       콜레스테롤     공복혈당       심전도  \
성별
0   55.677083  1.041667  133.083333  261.302083  0.12500  0.572917
1   53.758454  0.932367  130.946860  239.289855  0.15942  0.507246

         최대심박수   운동유발협심증     ST우울증   운동후ST경사     주요혈관수      결함유형    심장질환여부
성별
0   151.125000  0.229167  0.876042  1.427083  0.552083  2.125000  0.750000
1   148.961353  0.371981  1.115459  1.386473  0.811594  2.400966  0.449275

In [ ]:
# 2. 그룹화된 데이터 집계
grouped_stats = grouped.agg({'나이' : ['max', 'min'],
                             '콜레스테롤' : ['mean', 'std']
                            })

print(grouped_stats)        ## 보이듯이 멀티 칼럼 형식의 데이터를 만들어준다

    나이           콜레스테롤
   max min        mean        std
성별
0   76  34  261.302083  65.088946
1   77  29  239.289855  42.782392

In [ ]:
# 3. 성별과 흉통유형을 기준으로 그룹화
grouped_multi = df.groupby(['성별', '흉통유형']).mean()     ## 두 가지 기준 그루핑 : 멀티 인덱스

print("\n성별과 흉통유형별 주요 열의 평균:")
print(grouped_multi)            ## 마찬가지로 멀티 인덱스 형식의 데이터를 보여준다

성별과 흉통유형별 주요 열의 평균:
                나이       안정시혈압       콜레스테롤      공복혈당       심전도       최대심박수  \
성별 흉통유형
0  0     57.256410  138.589744  267.538462  0.128205  0.538462  145.282051
   1     51.944444  128.055556  251.444444  0.111111  0.555556  162.833333
   2     54.971429  127.885714  261.057143  0.114286  0.600000  151.800000
   3     63.250000  147.500000  247.000000  0.250000  0.750000  149.500000
1  0     55.105769  129.557692  243.605769  0.125000  0.451923  138.759615
   1     51.031250  128.593750  241.031250  0.093750  0.656250  162.187500
   2     52.538462  132.057692  231.134615  0.250000  0.596154  158.173077
   3     54.315789  139.473684  235.052632  0.210526  0.315789  157.315789

          운동유발협심증     ST우울증   운동후ST경사     주요혈관수      결함유형    심장질환여부
성별 흉통유형
0  0     0.461538  1.356410  1.179487  0.820513  2.282051  0.461538
   1     0.111111  0.461111  1.666667  0.555556  2.000000  0.888889
   2     0.057143  0.474286  1.571429  0.257143  2.028571  0.971429
   3     0.000000  1.575000  1.500000  0.500000  2.000000  1.000000
1  0     0.596154  1.393269  1.288462  1.019231  2.509615  0.201923
   1     0.062500  0.234375  1.687500  0.343750  2.218750  0.781250
   2     0.173077  1.015385  1.461538  0.807692  2.326923  0.673077
   3     0.210526  1.352632  1.210526  0.473684  2.315789  0.631579

## 2. 피벗테이블

In [ ]:
'''
피봇테이블은 데이터를 특정 기준에 따라 요약하거나 변환하는데 사용하는 도구이다.
pandas 라이브러리에서 제공하는 기능은 엑셀과 유사하며,
데이터를 행, 열, 값으로 구성하여 다양한 방식으로 요약할 수 있다.

    df.pivot_table()     
'''

In [2]:
import pandas as pd

# 데이터 로드
file_path = "datasets/heart.csv"
df = pd.read_csv(file_path)

# 컬럼명 변경
df.columns = ['나이', '성별', '흉통유형', '안정시혈압', '콜레스테롤', '공복혈당', '심전도',
              '최대심박수', '운동유발협심증', 'ST우울증', '운동후ST경사', '주요혈관수',
              '결함유형', '심장질환여부']

In [3]:
# 피벗테이블 생성
pivot = df.pivot_table(index= '성별', columns='흉통유형', values= '최대심박수', aggfunc= ['mean', 'max'])
'''
index: 그래프 왼쪽 (그루핑)
column: 그래프 위쪽 (집계)
values: 계산 대상 값들
aggfunc: values에 행할 계산

따라서 위의 코드는 종을 성별, 횡을 흉통유형으로 둔 채로 최대 심박수의 평균과 최댓값을 계산하는 코드이다
'''
## 위의 모든 항목들 [] 리스트 형식으로 묶어 멀티인덱스나 멀티 칼럼도 가능함

print('####성별과 흉통유형별 평균 최대 심박수####\n')
print(pivot)

####성별과 흉통유형별 평균 최대 심박수####

            mean                                      max
흉통유형           0           1           2           3    0    1    2    3
성별
0     145.282051  162.833333  151.800000  149.500000  182  192  179  171
1     138.759615  162.187500  158.173077  157.315789  186  202  194  190

In [6]:
pivot_multi_index = df.pivot_table(index = ['성별', '흉통유형'], values= '최대심박수', aggfunc= ['mean', 'max'])

print(pivot_multi_index)

               mean   max
              최대심박수 최대심박수
성별 흉통유형
0  0     145.282051   182
   1     162.833333   192
   2     151.800000   179
   3     149.500000   171
1  0     138.759615   186
   1     162.187500   202
   2     158.173077   194
   3     157.315789   190

### 결측치가 있을 때 피봇테이블

In [7]:
# 데이터 생성
data = {
    '성별': ['남성', '여성', '남성', '여성'],
    '흉통유형': [1, 2, 3, 1],
    '최대심박수': [150, 160, 155, 145]
}
df = pd.DataFrame(data)

# 피벗테이블 생성
pivot = df.pivot_table(index='성별', columns='흉통유형', values='최대심박수', aggfunc='mean')

# 결과 출력
print("피벗테이블 (결측값 포함):")
pivot

피벗테이블 (결측값 포함):

흉통유형      1      2      3
성별
남성    150.0    NaN  155.0
여성    145.0  160.0    NaN

In [10]:
pivot_with_NaN = df.pivot_table(index = '성별', columns = '흉통유형', values = '최대심박수', aggfunc= 'mean', fill_value= 0)

## fill_value=   -> 결측치를 채우는 매개변수

print('결측치를 채운 피벗테이블:')
print(pivot_with_NaN)

결측치를 채운 피벗테이블:
흉통유형      1      2      3
성별
남성    150.0    0.0  155.0
여성    145.0  160.0    0.0

In [9]:
# 열 평균값으로 대체하고자 할 때
pivot_mean_filled = pivot.apply(lambda x: x.fillna(x.mean()), axis=0)
# 결과 출력
print("\n열 기준 평균값으로 대체한 피벗테이블:")
pivot_mean_filled

열 기준 평균값으로 대체한 피벗테이블:

흉통유형      1      2      3
성별
남성    150.0  160.0  155.0
여성    145.0  160.0  155.0

In [11]:
# 피벗테이블 생성 후 결측값을 999로 대체
pivot_specific_value = pivot.fillna(999)
# 결과 출력
print("\n결측값을 특정 값(999)으로 대체한 피벗테이블:")
pivot_specific_value

결측값을 특정 값(999)으로 대체한 피벗테이블:

흉통유형      1      2      3
성별
남성    150.0  999.0  155.0
여성    145.0  160.0  999.0

## 3. 인덱스와 컬럼 계층 변경

In [ ]:
'''
인덱스 계층(multi - index)이란 여러 개의 인덱스 레벨을 사용해 데이터를 계층적으로 관리하는 방법이다.

마찬가지, 칼럼 계층(multi - column)이란 여러 칼럼 레벨을 사용해 데이터를 다차원으로 표시하는 방법이다.
'''

In [12]:
import pandas as pd

# 데이터 로드
file_path = "datasets/heart.csv"
df = pd.read_csv(file_path)

# 컬럼명 변경
df.columns = ['나이', '성별', '흉통유형', '안정시혈압', '콜레스테롤', '공복혈당', '심전도',
              '최대심박수', '운동유발협심증', 'ST우울증', '운동후ST경사', '주요혈관수',
              '결함유형', '심장질환여부']

### 멀티 인덱스 피봇테이블

In [13]:
grouped = df.groupby(['성별', '흉통유형']).mean()

# 성별과 흉통유형을 기준으로 그룹화(인덱싱) 한 DataFrame
print(grouped)

                나이       안정시혈압       콜레스테롤      공복혈당       심전도       최대심박수  \
성별 흉통유형
0  0     57.256410  138.589744  267.538462  0.128205  0.538462  145.282051
   1     51.944444  128.055556  251.444444  0.111111  0.555556  162.833333
   2     54.971429  127.885714  261.057143  0.114286  0.600000  151.800000
   3     63.250000  147.500000  247.000000  0.250000  0.750000  149.500000
1  0     55.105769  129.557692  243.605769  0.125000  0.451923  138.759615
   1     51.031250  128.593750  241.031250  0.093750  0.656250  162.187500
   2     52.538462  132.057692  231.134615  0.250000  0.596154  158.173077
   3     54.315789  139.473684  235.052632  0.210526  0.315789  157.315789

          운동유발협심증     ST우울증   운동후ST경사     주요혈관수      결함유형    심장질환여부
성별 흉통유형
0  0     0.461538  1.356410  1.179487  0.820513  2.282051  0.461538
   1     0.111111  0.461111  1.666667  0.555556  2.000000  0.888889
   2     0.057143  0.474286  1.571429  0.257143  2.028571  0.971429
   3     0.000000  1.575000  1.500000  0.500000  2.000000  1.000000
1  0     0.596154  1.393269  1.288462  1.019231  2.509615  0.201923
   1     0.062500  0.234375  1.687500  0.343750  2.218750  0.781250
   2     0.173077  1.015385  1.461538  0.807692  2.326923  0.673077
   3     0.210526  1.352632  1.210526  0.473684  2.315789  0.631579

### 인덱스 초기화

In [15]:
group_reset = grouped.reset_index()

print('멀티인덱스가 초기화된 모습의 데이터프레임')
print(group_reset)

멀티인덱스가 초기화된 모습의 데이터프레임
   성별  흉통유형         나이       안정시혈압       콜레스테롤      공복혈당       심전도  \
0   0     0  57.256410  138.589744  267.538462  0.128205  0.538462
1   0     1  51.944444  128.055556  251.444444  0.111111  0.555556
2   0     2  54.971429  127.885714  261.057143  0.114286  0.600000
3   0     3  63.250000  147.500000  247.000000  0.250000  0.750000
4   1     0  55.105769  129.557692  243.605769  0.125000  0.451923
5   1     1  51.031250  128.593750  241.031250  0.093750  0.656250
6   1     2  52.538462  132.057692  231.134615  0.250000  0.596154
7   1     3  54.315789  139.473684  235.052632  0.210526  0.315789

        최대심박수   운동유발협심증     ST우울증   운동후ST경사     주요혈관수      결함유형    심장질환여부
0  145.282051  0.461538  1.356410  1.179487  0.820513  2.282051  0.461538
1  162.833333  0.111111  0.461111  1.666667  0.555556  2.000000  0.888889
2  151.800000  0.057143  0.474286  1.571429  0.257143  2.028571  0.971429
3  149.500000  0.000000  1.575000  1.500000  0.500000  2.000000  1.000000
4  138.759615  0.596154  1.393269  1.288462  1.019231  2.509615  0.201923
5  162.187500  0.062500  0.234375  1.687500  0.343750  2.218750  0.781250
6  158.173077  0.173077  1.015385  1.461538  0.807692  2.326923  0.673077
7  157.315789  0.210526  1.352632  1.210526  0.473684  2.315789  0.631579

### 멀티 컬럼 피봇테이블

In [17]:
pivot_multi_column = df.pivot_table(index= '성별', columns=['흉통유형', '운동후ST경사'], values= '최대심박수', aggfunc= 'mean')

print(pivot_multi_column)

흉통유형          0                              1                           2  \
운동후ST경사       0           1           2      0           1       2       0
성별
0        146.00  139.000000  161.400000    NaN  160.500000  164.00  160.00
1        126.75  128.431034  157.052632  168.5  139.833333  167.25  171.25

흉통유형                                 3
운동후ST경사           1           2      0           1           2
성별
0        149.153846  153.047619  114.0         NaN  161.333333
1        147.250000  164.107143  147.5  159.272727  157.000000

## 4. 데이터 병합과 추가

### 4-1. 데이터 병합

In [ ]:
'''
동일한 칼럼을 가지고 있는 두 개의 데이터를 병합한다.

    merge()
        on= 공통 칼럼이며, 병합의 기준이 되는 칼럼이다.
        how= 병합 방식으로, 'inner' 'outer' 'left' 'right' 'cross'등이 가능하다. 
            'inner'
            두 데이터의 공통 칼럼 중 교집합만 가져옴
            'outer'
            두 데이터의 합집합. 모두 가져옴
            'left'
            왼쪽 데이터(첫번째)에 오른쪽 데이터를 붙임. 왼쪽 데이터는 모든 행을 유지함
            'right'
            오른쪽 데이터(두번째)에 오른쪽 데이터를 붙임. 오른쪽 데이터는 모든 행을 유지함
'''

In [25]:
import pandas as pd

# 첫 번째 데이터프레임 생성
data1 = {
    '제품ID': [1, 2, 3],
    '제품명': ['노트북', '모니터', '키보드']
}
df1 = pd.DataFrame(data1)

# 두 번째 데이터프레임 생성
data2 = {
    '제품ID': [1, 2, 4],
    '가격': [1000, 200, 50]
}
df2 = pd.DataFrame(data2)

# 데이터프레임 출력
print("첫 번째 데이터프레임:")
print(df1)
print("\n두 번째 데이터프레임:")
print(df2)

첫 번째 데이터프레임:
   제품ID  제품명
0     1  노트북
1     2  모니터
2     3  키보드

두 번째 데이터프레임:
   제품ID    가격
0     1  1000
1     2   200
2     4    50

#### 4-1-1. 내부 조인과 외부 조인

In [ ]:
# 내부 조인 - 교집합
inner_join = pd.merge(df1, df2, on='제품ID', how='inner')

# 데이터프레임 출력
print("첫 번째 데이터프레임:")
print(df1)
print("\n두 번째 데이터프레임:")
print(df2)
print("\n내부 조인 결과:")
print(inner_join)

첫 번째 데이터프레임:
   제품ID  제품명
0     1  노트북
1     2  모니터
2     3  키보드

두 번째 데이터프레임:
   제품ID    가격
0     1  1000
1     2   200
2     4    50

내부 조인 결과:
   제품ID  제품명    가격
0     1  노트북  1000
1     2  모니터   200

In [27]:
# 외부 조인 - 합집합
outer_join = pd.merge(df1, df2, on='제품ID', how='outer')

# 데이터프레임 출력
print("첫 번째 데이터프레임:")
print(df1)
print("\n두 번째 데이터프레임:")
print(df2)
print("\n외부 조인 결과:")
print(outer_join)

첫 번째 데이터프레임:
   제품ID  제품명
0     1  노트북
1     2  모니터
2     3  키보드

두 번째 데이터프레임:
   제품ID    가격
0     1  1000
1     2   200
2     4    50

외부 조인 결과:
   제품ID  제품명      가격
0     1  노트북  1000.0
1     2  모니터   200.0
2     3  키보드     NaN
3     4  NaN    50.0

#### 4-1-2. 왼쪽 조인과 오른쪽 조인

In [28]:
# 왼쪽 조인 - 첫번째에 두번째 붙이기
left_join = pd.merge(df1, df2, on='제품ID', how='left')

# 데이터프레임 출력
print("첫 번째 데이터프레임:")
print(df1)
print("\n두 번째 데이터프레임:")
print(df2)
print("\n왼쪽 조인 결과:")
print(left_join)

첫 번째 데이터프레임:
   제품ID  제품명
0     1  노트북
1     2  모니터
2     3  키보드

두 번째 데이터프레임:
   제품ID    가격
0     1  1000
1     2   200
2     4    50

왼쪽 조인 결과:
   제품ID  제품명      가격
0     1  노트북  1000.0
1     2  모니터   200.0
2     3  키보드     NaN

In [29]:
# 오른쪽 조인 - 두번째에 첫번째 붙이기
right_join = pd.merge(df1, df2, on='제품ID', how='right')

# 데이터프레임 출력
print("첫 번째 데이터프레임:")
print(df1)
print("\n두 번째 데이터프레임:")
print(df2)
print("\n오른쪽 조인 결과:")
print(right_join)

첫 번째 데이터프레임:
   제품ID  제품명
0     1  노트북
1     2  모니터
2     3  키보드

두 번째 데이터프레임:
   제품ID    가격
0     1  1000
1     2   200
2     4    50

오른쪽 조인 결과:
   제품ID  제품명    가격
0     1  노트북  1000
1     2  모니터   200
2     4  NaN    50

#### 4-1-3. 교차 조인

In [33]:
# 교차 조인 
cross_join = pd.merge(df1, df2, how='cross') 

# 데이터프레임 출력
print("첫 번째 데이터프레임:")
print(df1)
print("\n두 번째 데이터프레임:")
print(df2)
print("\n교차 조인 결과:") 
print(cross_join)

첫 번째 데이터프레임:
   제품ID  제품명
0     1  노트북
1     2  모니터
2     3  키보드

두 번째 데이터프레임:
   제품ID    가격
0     1  1000
1     2   200
2     4    50

교차 조인 결과:
   제품ID_x  제품명  제품ID_y    가격
0       1  노트북       1  1000
1       1  노트북       2   200
2       1  노트북       4    50
3       2  모니터       1  1000
4       2  모니터       2   200
5       2  모니터       4    50
6       3  키보드       1  1000
7       3  키보드       2   200
8       3  키보드       4    50

### 4-2. 데이터 추가

In [ ]:
'''
데이터 병합(join)이 다른 열을 가진 데이터를 합치는 과정이라면,
데이터 추가(union)은 동일한 열을 가진 데이터를 세로로 확장하는 작업이다.

데이터 추가에서는 concat()을 사용할 것이다.
'''

In [34]:
# 첫 번째 데이터프레임 생성
data1 = {
    '이름': ['홍길동', '이순신'],
    '나이': [30, 40]
}
df1 = pd.DataFrame(data1)

# 두 번째 데이터프레임 생성
data2 = {
    '이름': ['강감찬', '유관순'],
    '나이': [50, 20]
}
df2 = pd.DataFrame(data2)

# 데이터프레임 출력
print("첫 번째 데이터프레임:")
print(df1)
print("\n두 번째 데이터프레임:")
print(df2)

첫 번째 데이터프레임:
    이름  나이
0  홍길동  30
1  이순신  40

두 번째 데이터프레임:
    이름  나이
0  강감찬  50
1  유관순  20

#### 4-2-1. 같은 column을 가진 데이터의 결합(union)

In [41]:
union_df = pd.concat([df1, df2], ignore_index=True)         ## ignore_index : 기존 데이터프레임 왼쪽의 인덱스 (0,1,2~)를 무시할건지

print("## 첫번째 df")
print(df1)

print('\n## 두번째 df')
print(df2)

print('\n## 결합된 df')
print(union_df)

## 첫번째 df
    이름  나이
0  홍길동  30
1  이순신  40

## 두번째 df
    이름  나이
0  강감찬  50
1  유관순  20

## 결합된 df
    이름  나이
0  홍길동  30
1  이순신  40
2  강감찬  50
3  유관순  20

#### 4-2-2. 다른 column을 가진 데이터의 결합

In [40]:
# 열이 다른 데이터프레임 생성
data3 = {
    '이름': ['정약용', '김유신'],
    '주소': ['서울', '경주']
}
df3 = pd.DataFrame(data3)

# 데이터프레임 결합
union_with_different_columns = pd.concat([df1, df2, df3], ignore_index=True)

print("## 첫번째 df")
print(df1)

print('\n## 두번째 df')
print(df2)

print('\n## 세번째 df')
print(df3)

print("\n열이 다른 데이터프레임 결합 결과:")
print(union_with_different_columns)

## 첫번째 df
    이름  나이
0  홍길동  30
1  이순신  40

## 두번째 df
    이름  나이
0  강감찬  50
1  유관순  20

## 세번째 df
    이름  주소
0  정약용  서울
1  김유신  경주

열이 다른 데이터프레임 결합 결과:
    이름    나이   주소
0  홍길동  30.0  NaN
1  이순신  40.0  NaN
2  강감찬  50.0  NaN
3  유관순  20.0  NaN
4  정약용   NaN   서울
5  김유신   NaN   경주

## 5. 데이터 파생 - 변수(column) 생성

In [44]:
import pandas as pd
import numpy as np

# 샘플 데이터 생성
df = pd.DataFrame({
    '이름' : ['철수','영희','민수','지수'],
    '나이' : [23, 35, 45, 52],
    '월급' : [250, 400, 600, 700]
})

# 연령대 변수 생성
df['연령대'] = pd.cut(df['나이'], bins= [0,30,40,50,100],
                   labels= ['20대', '30대', '40대', '50대 이상'])

# 누적 월급 계산
df['누적 월급'] = df['월급'].cumsum()

# 편차 계산
df['월급_편차'] = df['월급'] - df['월급'].mean()

# 로그 변환 (로그화)
df['월급_로그화'] = np.log1p(df['월급'])

print(df)

   이름  나이   월급     연령대  누적 월급  월급_편차    월급_로그화
0  철수  23  250     20대    250 -237.5  5.525453
1  영희  35  400     30대    650  -87.5  5.993961
2  민수  45  600     40대   1250  112.5  6.398595
3  지수  52  700  50대 이상   1950  212.5  6.552508

In [51]:
df = pd.DataFrame({
    '이름' : ['철수','영희','민수','지수'],
    '성별' : ['남','여','남','여'],
    '주소' : ['서울 강남구','부산 해운대구','서울 종로구','대전 서구']
})

# 성별을 코드로 변환
df['성별_코드'] = df['성별'].map({'여' : 0, '남' : 1})

# 주소에서 도시와 구 추출
df['도시'] = df['주소'].str.split(" ").str[0]
df['구'] = df['주소'].str.split(" ").str[1]

print(df)

   이름 성별       주소  성별_코드  도시     구
0  철수  남   서울 강남구      1  서울   강남구
1  영희  여  부산 해운대구      0  부산  해운대구
2  민수  남   서울 종로구      1  서울   종로구
3  지수  여    대전 서구      0  대전    서구

In [50]:
# 혹은 주소를 한 번에 분할해서 도시와 구 컬럼 생성
df[['도시', '구']] = df['주소'].str.split(" ", expand=True)

print(df)

   이름 성별       주소  성별_코드  도시     구
0  철수  남   서울 강남구      1  서울   강남구
1  영희  여  부산 해운대구      0  부산  해운대구
2  민수  남   서울 종로구      1  서울   종로구
3  지수  여    대전 서구      0  대전    서구